# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web Accessibility Demo
email: dzul1983@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a simple demo website demonstrating the implementation of web accessibility
  in commonly used website components.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dnasir.github.io/web-accessibility-demo" # the base hostname & protocol for your site
twitter_username: dzul1983
github_username:  dnasir

# Build settings
markdown: kramdown
sass:
  load_paths:
    - node_modules/bootstrap-sass/assets/stylesheets
    - _sass
  # loading path from site root
  # default to _sass
  #sass_dir: node_modules/bootstrap-sass/assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  style: nested

exclude:
    - 'node_modules/**/Gemfile'
    - 'node_modules/**/LICENSE'
    - 'node_modules/**/Rakefile'
    - 'node_modules/**/*.rake'
    - 'node_modules/**/*.rb'
    - 'node_modules/**/*.xml'
    - 'node_modules/**/*.json'
    - 'node_modules/**/*.gemspec'
    - 'node_modules/**/*.md'
    - 'node_modules/**/*.sass'
    - 'node_modules/**/test'
    - 'node_modules/**/*.txt'